version: '0.1'
services:
  mqtt:
    #image: eclipse-mosquitto  # MQTT 브로커 이미지
    build: ./mqtt-client  # FastAPI 앱이 있는 디렉토리
    environment:  # 환경 변수 설정
      - AZURE_CONNECTION_STRING=${AZURE_CONNECTION_STRING}
      - GET_ANOMALY_DATA_URL=${GET_ANOMALY_DATA_URL}
      - RESOURCE_PATH=${RESOURCE_PATH}
    volumes:
      - ./resources:/app/resources  # 공유 폴더 설정
      - ./config.py:/app/config.py

  fastapi:
    build: ./anomaly-detection-server  # FastAPI 앱이 있는 디렉토리
    environment:  # 환경 변수 설정
      - FASTAPI_HOST=${FASTAPI_HOST}
      - FASTAPI_PORT=${FASTAPI_PORT}
      - RESOURCE_PATH=${RESOURCE_PATH}
    volumes:
      - ./resources:/app/resources  # 공유 폴더 설정
      - ./config.py:/app/config.py
    ports:
      - ${FASTAPI_PORT}:${FASTAPI_PORT}  # FastAPI 앱 포트 매핑
    #depends_on:
    #  - mqtt  # MQTT 서비스가 먼저 시작되도록 설정
